-- ============================================================
-- FieldMS schema verification.
--
-- READ ONLY. Creates nothing, changes nothing, deletes nothing.
--
-- GENERATED FILE — do not edit by hand.
--   Produced by scripts/build-verify-sql.mjs from the same scanner that
--   backs `npm run doctor`. Regenerate with:  npm run build:verify
--
-- WHY THIS EXISTS
--   The repo's migration files did not match this database. Migrations 004
--   and 006 to 021 had never been applied, so about two thirds of the tables
--   the app queries did not exist. Nothing surfaced that, because a missing
--   table makes a page render empty rather than crash.
--
--   The expected schema below was generated by scanning every .from() and
--   .select() call in the codebase: 47 tables and views, 202
--   column references. It describes what the app actually needs, not what
--   anyone assumed it needed.
--
-- HOW TO USE
--   Paste into the Supabase SQL Editor and Run.
--   Every row returned is something the app expects and cannot find.
--   NO ROWS MEANS THE DATABASE SATISFIES EVERY QUERY IN THE CODEBASE.
--
--   Run it after any migration, and before any release.
-- ============================================================

WITH expected(obj, kind, cols) AS (
  VALUES
    ('accounting_sync_records', 'table', ARRAY['attempts', 'external_id', 'id', 'idempotency_key', 'tenant_id']::text[]),
    ('asset_types', 'table', ARRAY['sort_order']::text[]),
    ('assets', 'table', ARRAY[NULL]::text[]),
    ('billing_audit_events', 'table', ARRAY['created_at', 'job_id']::text[]),
    ('company_announcements', 'table', ARRAY['created_at', 'id', 'tenant_id']::text[]),
    ('compliance_register', 'view', ARRAY['next_test_due', 'tenant_id']::text[]),
    ('customer_marketing_list', 'view', ARRAY['lifetime_value', 'tenant_id']::text[]),
    ('customers', 'table', ARRAY['id', 'name', 'tenant_id', 'unsubscribe_token', 'unsubscribed_at']::text[]),
    ('estimate_approval_events', 'table', ARRAY[NULL]::text[]),
    ('estimate_items', 'table', ARRAY['id', 'name', 'quantity', 'total', 'unit_price']::text[]),
    ('estimates', 'table', ARRAY['approval_name', 'approval_note', 'approved_at', 'business_id', 'created_at', 'customer_email', 'customer_name', 'customer_phone', 'declined_at', 'deposit_percent', 'id', 'job_id', 'public_token', 'sent_at', 'status', 'total', 'updated_at']::text[]),
    ('form_audit_events', 'table', ARRAY['created_at', 'submission_id']::text[]),
    ('form_signatures', 'table', ARRAY['role', 'signature_data', 'signed_at', 'signer_name', 'submission_id']::text[]),
    ('form_submissions', 'table', ARRAY['created_at', 'id', 'job_id', 'public_token', 'template_id', 'tenant_id']::text[]),
    ('form_templates', 'table', ARRAY['archived', 'auto_on_job_complete', 'id', 'name', 'tenant_id']::text[]),
    ('integrations', 'table', ARRAY['id', 'provider', 'status', 'tenant_id']::text[]),
    ('job_assignments', 'table', ARRAY['job_id']::text[]),
    ('job_billing_items', 'table', ARRAY['created_at', 'job_id', 'tenant_id']::text[]),
    ('job_events', 'table', ARRAY['created_at', 'job_id']::text[]),
    ('job_invoice_items', 'table', ARRAY[NULL]::text[]),
    ('job_invoices', 'table', ARRAY['created_at', 'id', 'job_id', 'public_token']::text[]),
    ('job_location_updates', 'table', ARRAY['job_id', 'recorded_at']::text[]),
    ('job_payments', 'table', ARRAY['id', 'job_id', 'received_at']::text[]),
    ('job_photos', 'table', ARRAY['caption', 'file_path', 'id', 'job_id', 'taken_at']::text[]),
    ('job_plans', 'table', ARRAY['created_at', 'id', 'tenant_id']::text[]),
    ('job_reports', 'table', ARRAY['created_at', 'id', 'tenant_id', 'token']::text[]),
    ('job_test_sheets', 'table', ARRAY['asset_id', 'certificate_number', 'certificate_token', 'circuits', 'completed_at', 'created_at', 'id', 'job_id', 'notes', 'status', 'tenant_id', 'test_date', 'tester_name']::text[]),
    ('job_tracking_tokens', 'table', ARRAY['job_id', 'token']::text[]),
    ('job_variations', 'table', ARRAY['id', 'job_id', 'public_token', 'variation_number']::text[]),
    ('jobs', 'table', ARRAY['assigned_to', 'created_at', 'customer_address', 'customer_email', 'customer_id', 'customer_name', 'customer_phone', 'description', 'due_date', 'gst_rate', 'id', 'po_number', 'quote_total', 'status', 'tenant_id', 'title', 'updated_at']::text[]),
    ('master_products', 'table', ARRAY['aliases', 'id', 'mpn', 'name']::text[]),
    ('price_alerts', 'table', ARRAY['created_at', 'read', 'tenant_id']::text[]),
    ('price_changes', 'table', ARRAY['master_product_id', 'new_price', 'old_price', 'pct_change', 'recorded_at', 'supplier_key']::text[]),
    ('price_snapshots', 'table', ARRAY['price', 'recorded_at', 'supplier_product_id']::text[]),
    ('profiles', 'table', ARRAY['email', 'full_name', 'id']::text[]),
    ('sites', 'table', ARRAY['address', 'customer_id']::text[]),
    ('supplier_products', 'table', ARRAY['id', 'master_product_id', 'price', 'sku', 'supplier_key', 'supplier_name']::text[]),
    ('sync_runs', 'table', ARRAY['id']::text[]),
    ('tenant_branding', 'table', ARRAY['accent_color', 'acn', 'business_address', 'electrical_license', 'email_signature', 'font_family', 'footer_text', 'logo_path', 'primary_color', 'secondary_color', 'tenant_id', 'trading_name']::text[]),
    ('tenant_members', 'table', ARRAY['id', 'role', 'tenant_id', 'user_id']::text[]),
    ('tenant_onboarding', 'table', ARRAY['tenant_id', 'trades']::text[]),
    ('tenant_price_overrides', 'table', ARRAY['master_product_id', 'price', 'tenant_id', 'updated_at']::text[]),
    ('tenant_pricing_settings', 'table', ARRAY['alert_threshold_pct', 'tenant_id']::text[]),
    ('tenant_supplier_accounts', 'table', ARRAY['account_reference', 'created_at', 'id', 'last_synced_at', 'status', 'supplier_key', 'sync_frequency', 'tenant_id']::text[]),
    ('tenant_trade_prices', 'table', ARRAY['last_updated', 'price', 'tenant_id']::text[]),
    ('tenants', 'table', ARRAY['abn', 'id', 'logo_url', 'name', 'phone', 'website']::text[]),
    ('time_entries', 'table', ARRAY['ended_at', 'id', 'started_at', 'submitted', 'tenant_id', 'user_id']::text[])
),

-- ── Missing tables and views ────────────────────────────────
missing_objects AS (
  SELECT 1 AS sort,
         'MISSING ' || upper(e.kind) AS problem,
         e.obj AS object_name,
         NULL::text AS detail
    FROM expected e
   WHERE to_regclass('public.' || e.obj) IS NULL
),

-- ── Missing columns on objects that do exist ────────────────
missing_columns AS (
  SELECT 2 AS sort, 'MISSING COLUMN' AS problem, e.obj AS object_name, c AS detail
    FROM expected e
    CROSS JOIN LATERAL unnest(e.cols) AS c
   WHERE to_regclass('public.' || e.obj) IS NOT NULL
     AND c IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM information_schema.columns ic
        WHERE ic.table_schema = 'public'
          AND ic.table_name = e.obj
          AND ic.column_name = c
     )
),

-- ── Functions the app or its RLS policies call ──────────────
missing_functions AS (
  SELECT 3 AS sort, 'MISSING FUNCTION' AS problem, f AS object_name, NULL::text AS detail
    FROM unnest(ARRAY['create_tenant_with_owner', 'next_document_number', 'set_updated_at', 'is_office', 'is_owner', 'is_member', 'techs_see_all', 'my_role', 'bump_asset_test_dates']) AS f
   WHERE NOT EXISTS (
     SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public' AND p.proname = f
   )
),

-- ── Storage buckets for logos, plans and site photos ────────
missing_buckets AS (
  SELECT 4 AS sort, 'MISSING BUCKET' AS problem, b AS object_name, NULL::text AS detail
    FROM unnest(ARRAY['branding', 'job-photos', 'job-plans']) AS b
   WHERE to_regclass('storage.buckets') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM storage.buckets sb WHERE sb.id = b)
),

-- ── Tenant data with RLS switched off: a cross customer leak ─
rls_off AS (
  SELECT 5 AS sort, 'RLS DISABLED' AS problem, c.relname AS object_name,
         'tenant data readable across workspaces' AS detail
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relkind = 'r' AND NOT c.relrowsecurity
     AND EXISTS (
       SELECT 1 FROM information_schema.columns ic
        WHERE ic.table_schema = 'public' AND ic.table_name = c.relname
          AND ic.column_name IN ('tenant_id','business_id')
     )
),

-- ── Child tables with RLS off ───────────────────────────────
-- A line item table usually has no tenant_id of its own; it inherits its
-- scope from a parent that does. The check above cannot see those, so this
-- one follows foreign keys instead. estimate_items, job_invoice_items and
-- form_signatures all live here: leaving RLS off on one exposes every
-- workspace's quote and invoice lines to any signed in user.
rls_off_child AS (
  SELECT DISTINCT 5 AS sort, 'RLS DISABLED' AS problem, child.relname AS object_name,
         'child of ' || parent.relname || ', which is tenant scoped' AS detail
    FROM pg_constraint fk
    JOIN pg_class child  ON child.oid  = fk.conrelid
    JOIN pg_class parent ON parent.oid = fk.confrelid
    JOIN pg_namespace n  ON n.oid = child.relnamespace
   WHERE fk.contype = 'f'
     AND n.nspname = 'public'
     AND child.relkind = 'r'
     AND NOT child.relrowsecurity
     AND EXISTS (
       SELECT 1 FROM information_schema.columns ic
        WHERE ic.table_schema = 'public' AND ic.table_name = parent.relname
          AND ic.column_name IN ('tenant_id','business_id')
     )
     AND NOT EXISTS (
       SELECT 1 FROM information_schema.columns ic
        WHERE ic.table_schema = 'public' AND ic.table_name = child.relname
          AND ic.column_name IN ('tenant_id','business_id')
     )
),

-- ── RLS on with no policies: every query silently returns none ─
rls_no_policy AS (
  SELECT 6 AS sort, 'RLS BUT NO POLICY' AS problem, c.relname AS object_name,
         'every query returns zero rows' AS detail
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
   WHERE n.nspname = 'public' AND c.relkind = 'r' AND c.relrowsecurity
     AND NOT EXISTS (
       SELECT 1 FROM pg_policies p WHERE p.schemaname = 'public' AND p.tablename = c.relname
     )
),

problems AS (
    SELECT * FROM missing_objects
    UNION ALL SELECT * FROM missing_columns
    UNION ALL SELECT * FROM missing_functions
    UNION ALL SELECT * FROM missing_buckets
    UNION ALL SELECT * FROM rls_off
    UNION ALL SELECT * FROM rls_off_child
    UNION ALL SELECT * FROM rls_no_policy
)

SELECT problem, object_name, detail
  FROM problems
 ORDER BY sort, object_name, detail;
