import type { EquipmentItem } from '@/types/database'

export const EQUIPMENT_SUPPLIERS = [
  { id: 'all', name: 'All suppliers' },
  { id: 'sparkydirect', name: 'SparkyDirect' },
  { id: 'cnw', name: 'CNW' },
] as const

export const SPARKY_DIRECT_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'click-deco-antique-brass-euro-media-plate',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Antique Brass 1G 1 Module Euro Media Plate',
    sku: 'CD-1G-EURO-MP',
    basePrice: 6.59,
  },
  {
    id: 'click-deco-antique-brass-single-switched-socket',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Antique Brass 1G 13A Single Switched Socket Black Insert',
    sku: 'CD-1G-13A-SS',
    basePrice: 7.06,
  },
  {
    id: 'click-deco-antique-brass-switched-fused-unit',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Antique Brass 1G 13A Switched Fused Connection Unit & Neon Black Insert',
    sku: 'CD-1G-13A-FCU',
    basePrice: 8.76,
  },
  {
    id: 'click-deco-antique-brass-unswitched-fused-unit',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Antique Brass 1G 13A Unswitched Fused Connection Unit Black Insert',
    sku: 'CD-1G-13A-UFCU',
    basePrice: 7.54,
  },
  {
    id: 'click-deco-antique-brass-single-dolly-switch',
    supplier: 'SparkyDirect',
    category: 'Switches',
    name: 'Click Deco Antique Brass 1G 2W Single Dolly Light Switch',
    sku: 'CD-1G-2W-DOLLY',
    basePrice: 8.94,
  },
  {
    id: 'click-deco-antique-brass-single-light-switch',
    supplier: 'SparkyDirect',
    category: 'Switches',
    name: 'Click Deco Antique Brass 1G 2W Single Light Switch Black Insert',
    sku: 'CD-1G-2W-LS',
    basePrice: 6.24,
  },
  {
    id: 'click-deco-antique-brass-45a-dp-switch',
    supplier: 'SparkyDirect',
    category: 'Switches',
    name: 'Click Deco Antique Brass 1G 45A DP Switch Black Insert',
    sku: 'CD-1G-45A-DP',
    basePrice: 9.99,
  },
  {
    id: 'click-deco-antique-brass-double-switched-socket',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Antique Brass 2G 13A Double Switched Socket Black Insert',
    sku: 'CD-2G-13A-DS',
    basePrice: 9.99,
  },
  {
    id: 'click-deco-antique-brass-single-blank-plate',
    supplier: 'SparkyDirect',
    category: 'Accessories',
    name: 'Click Deco Antique Brass 1G Single Blank Plate',
    sku: 'CD-1G-BLANK',
    basePrice: 4.93,
  },
  {
    id: 'click-deco-antique-brass-f-satellite-plate',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Antique Brass 1G F Satellite Outlet Plate Black Insert',
    sku: 'CD-1G-SAT',
    basePrice: 8.79,
  },
  {
    id: 'click-deco-black-nickel-single-usb-socket',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Black Nickel 1G 13A Single Switched Socket C/W 1 X USB Outlet',
    sku: 'CD-BN-1G-USB',
    basePrice: 15.99,
  },
  {
    id: 'click-deco-black-nickel-2g-double-dolly-switch',
    supplier: 'SparkyDirect',
    category: 'Switches',
    name: 'Click Deco Black Nickel 2G 2W Double Dolly Light Switch',
    sku: 'CD-BN-2G-DD',
    basePrice: 9.99,
  },
  {
    id: 'click-deco-black-nickel-single-switched-socket',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Click Deco Black Nickel 1G 13A Single Switched Socket Black Insert',
    sku: 'CD-BN-1G-SS',
    basePrice: 7.06,
  },
  {
    id: 'saxby-atlantis-single-adjustable-spotlight',
    supplier: 'SparkyDirect',
    category: 'Spotlights',
    name: 'Saxby Atlantis Coastal Single Adjustable Garden Spike IP65 Marine Grade Stainless Steel Spotlight',
    sku: 'SAX-ATL-SGL',
    basePrice: 50.99,
  },
  {
    id: 'saxby-atlantis-twin-280mm-spotlight',
    supplier: 'SparkyDirect',
    category: 'Spotlights',
    name: 'Saxby Atlantis Coastal Twin 280mm Adjustable Post Top IP65 Marine Grade Stainless Steel Spotlight',
    sku: 'SAX-ATL-TWN-280',
    basePrice: 126.99,
  },
  {
    id: 'saxby-atlantis-twin-up-down-spotlight',
    supplier: 'SparkyDirect',
    category: 'Spotlights',
    name: 'Saxby Atlantis Coastal Twin Up/Down Fixed IP65 Marine Grade Stainless Steel Spotlight',
    sku: 'SAX-ATL-TWN-UD',
    basePrice: 57.99,
  },
  {
    id: 'saxby-atlantis-single-fixed-spotlight',
    supplier: 'SparkyDirect',
    category: 'Spotlights',
    name: 'Saxby Atlantis Coastal Single Fixed IP65 Marine Grade Stainless Steel Spotlight',
    sku: 'SAX-ATL-FIX',
    basePrice: 50.99,
  },
  {
    id: 'saxby-pillared-wall-lantern',
    supplier: 'SparkyDirect',
    category: 'Outdoor lighting',
    name: 'Saxby 12W Wall Lantern IP44 Black',
    sku: 'SAX-LAN-12WB',
    basePrice: 39.99,
  },
  {
    id: 'saxby-10w-led-floodlight-black',
    supplier: 'SparkyDirect',
    category: 'Outdoor lighting',
    name: 'Saxby 10W LED Floodlight Black',
    sku: 'SAX-FL-10WB',
    basePrice: 29.99,
  },
  {
    id: 'saxby-pir-sensor-switch',
    supplier: 'SparkyDirect',
    category: 'Sensors',
    name: 'Saxby 1G PIR Sensor Switch White',
    sku: 'SAX-PIR-1GW',
    basePrice: 34.99,
  },
  {
    id: 'saxby-bulkhead-light-white',
    supplier: 'SparkyDirect',
    category: 'Outdoor lighting',
    name: 'Saxby 5W Bulkhead Light White',
    sku: 'SAX-BUL-5WW',
    basePrice: 19.99,
  },
  {
    id: 'scolmore-13a-single-switched-socket-white',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Scolmore 1G 13A Single Switched Socket White',
    sku: 'SC-1G-13A-SS-W',
    basePrice: 6.49,
  },
  {
    id: 'scolmore-2g-13a-double-switched-socket-white',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Scolmore 2G 13A Double Switched Socket Polar White',
    sku: 'SC-2G-13A-DS-PW',
    basePrice: 10.49,
  },
  {
    id: 'scolmore-1g-20a-dp-switch-white',
    supplier: 'SparkyDirect',
    category: 'Switches',
    name: 'Scolmore 1G 20A DP Switch White',
    sku: 'SC-1G-20A-DP-W',
    basePrice: 8.70,
  },
  {
    id: 'scolmore-1g-13a-usb-socket-white',
    supplier: 'SparkyDirect',
    category: 'Sockets & Switches',
    name: 'Scolmore 1G 13A USB Combined Socket White',
    sku: 'SC-1G-13A-USB-W',
    basePrice: 14.99,
  },
  {
    id: 'scolmore-1g-45a-dp-cooker-unit',
    supplier: 'SparkyDirect',
    category: 'Safety switches',
    name: 'Scolmore 1G 45A DP Cooker Control Unit Black Insert',
    sku: 'SC-1G-45A-CU-BI',
    basePrice: 14.99,
  },
  {
    id: 'sd-cable-tne-1-5mm-100m',
    supplier: 'SparkyDirect',
    category: 'Cables',
    name: 'SparkyDirect 1.5mm² Twin and Earth Cable 100m',
    sku: 'SD-TNE-1.5-100',
    basePrice: 98.50,
  },
  {
    id: 'sd-cable-tne-2-5mm-100m',
    supplier: 'SparkyDirect',
    category: 'Cables',
    name: 'SparkyDirect 2.5mm² Twin and Earth Cable 100m',
    sku: 'SD-TNE-2.5-100',
    basePrice: 128.75,
  },
  {
    id: 'sd-cable-single-core-6mm-100m',
    supplier: 'SparkyDirect',
    category: 'Cables',
    name: 'SparkyDirect 6mm² Single Core PVC Cable 100m',
    sku: 'SD-SC-6-100',
    basePrice: 220.00,
  },
  {
    id: 'sd-cable-single-core-10mm-100m',
    supplier: 'SparkyDirect',
    category: 'Cables',
    name: 'SparkyDirect 10mm² Single Core PVC Cable 100m',
    sku: 'SD-SC-10-100',
    basePrice: 310.00,
  },
  {
    id: 'sd-cable-single-core-16mm-100m',
    supplier: 'SparkyDirect',
    category: 'Cables',
    name: 'SparkyDirect 16mm² Single Core PVC Cable 100m',
    sku: 'SD-SC-16-100',
    basePrice: 405.00,
  },
]

export const CNW_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'cnw-1g-13a-switched-socket-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 1G 13A Switched Socket White',
    sku: 'CNW-1G-13A-SS-W',
    basePrice: 5.99,
  },
  {
    id: 'cnw-2g-13a-double-switched-socket-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 2G 13A Double Switched Socket White',
    sku: 'CNW-2G-13A-DS-W',
    basePrice: 9.49,
  },
  {
    id: 'cnw-1g-13a-single-unswitched-socket-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 1G 13A Single Unswitched Socket White',
    sku: 'CNW-1G-13A-US-W',
    basePrice: 4.99,
  },
  {
    id: 'cnw-1g-2w-single-light-switch-white',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 1G 2W Single Light Switch White',
    sku: 'CNW-1G-2W-LS-W',
    basePrice: 5.49,
  },
  {
    id: 'cnw-2g-2w-double-light-switch-white',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 2G 2W Double Light Switch White',
    sku: 'CNW-2G-2W-DLS-W',
    basePrice: 8.99,
  },
  {
    id: 'cnw-1g-13a-shaver-socket-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 1G 13A Shaver Socket White',
    sku: 'CNW-1G-SHAVER-W',
    basePrice: 39.99,
  },
  {
    id: 'cnw-1g-13a-usb-socket-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 1G 13A USB Socket White',
    sku: 'CNW-1G-13A-USB-W',
    basePrice: 12.99,
  },
  {
    id: 'cnw-1g-1-module-euro-media-plate-chrome',
    supplier: 'CNW',
    category: 'Accessories',
    name: 'CNW 1G 1 Module Euro Media Plate Chrome',
    sku: 'CNW-1G-EURO-MP-CH',
    basePrice: 6.29,
  },
  {
    id: 'cnw-1g-20a-dp-switch-white',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 1G 20A DP Switch White',
    sku: 'CNW-1G-20A-DP-W',
    basePrice: 8.49,
  },
  {
    id: 'cnw-1g-45a-dp-cooker-control-unit-white',
    supplier: 'CNW',
    category: 'Safety switches',
    name: 'CNW 1G 45A DP Cooker Control Unit White',
    sku: 'CNW-1G-45A-CU-W',
    basePrice: 13.49,
  },
  {
    id: 'cnw-security-floodlight-20w-black',
    supplier: 'CNW',
    category: 'Outdoor lighting',
    name: 'CNW 20W LED Security Floodlight Black',
    sku: 'CNW-FL-20W-BK',
    basePrice: 42.99,
  },
  {
    id: 'cnw-pir-sensor-light-white',
    supplier: 'CNW',
    category: 'Sensors',
    name: 'CNW PIR Sensor Light White',
    sku: 'CNW-PIR-W',
    basePrice: 36.99,
  },
  {
    id: 'cnw-wall-lantern-12w-black',
    supplier: 'CNW',
    category: 'Outdoor lighting',
    name: 'CNW 12W Wall Lantern Black',
    sku: 'CNW-LAN-12W-BK',
    basePrice: 41.99,
  },
  {
    id: 'cnw-surface-bulkhead-light-white',
    supplier: 'CNW',
    category: 'Outdoor lighting',
    name: 'CNW Surface Mounted Bulkhead Light White',
    sku: 'CNW-BULK-5W-W',
    basePrice: 18.49,
  },
  {
    id: 'cnw-1g-1-module-blank-plate-white',
    supplier: 'CNW',
    category: 'Accessories',
    name: 'CNW 1G 1 Module Blank Plate White',
    sku: 'CNW-1G-BLANK-W',
    basePrice: 3.99,
  },
  {
    id: 'cnw-1g-f-satellite-outlet-plate-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 1G F Satellite Outlet Plate White',
    sku: 'CNW-1G-SAT-W',
    basePrice: 8.49,
  },
  {
    id: 'cnw-1g-45a-dp-switch-black',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 1G 45A DP Switch Black',
    sku: 'CNW-1G-45A-DP-BK',
    basePrice: 10.49,
  },
  {
    id: 'cnw-1g-fan-isolator-switch-white',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 1G Fan Isolator Switch White',
    sku: 'CNW-1G-FAN-ISO-W',
    basePrice: 14.99,
  },
  {
    id: 'cnw-1g-bt-telephone-outlet-white',
    supplier: 'CNW',
    category: 'Data & comms',
    name: 'CNW 1G BT Telephone Outlet White',
    sku: 'CNW-1G-BT-W',
    basePrice: 9.99,
  },
  {
    id: 'cnw-1g-tv-coaxial-outlet-white',
    supplier: 'CNW',
    category: 'Data & comms',
    name: 'CNW 1G TV Coaxial Outlet White',
    sku: 'CNW-1G-TV-W',
    basePrice: 9.49,
  },
  {
    id: 'cnw-1g-2a-round-pin-socket-white',
    supplier: 'CNW',
    category: 'Sockets & Switches',
    name: 'CNW 1G 2A Round Pin Single Socket White',
    sku: 'CNW-1G-2A-RPS-W',
    basePrice: 6.99,
  },
  {
    id: 'cnw-1g-1-channel-dimmer-switch-white',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 1G 1 Channel Dimmer Switch White',
    sku: 'CNW-1G-DIM-W',
    basePrice: 13.99,
  },
  {
    id: 'cnw-1g-2w-single-dolly-switch-black',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 1G 2W Single Dolly Switch Black',
    sku: 'CNW-1G-2W-DOLLY-BK',
    basePrice: 8.49,
  },
  {
    id: 'cnw-2g-2w-double-dolly-switch-black',
    supplier: 'CNW',
    category: 'Switches',
    name: 'CNW 2G 2W Double Dolly Switch Black',
    sku: 'CNW-2G-2W-DD-BK',
    basePrice: 12.99,
  },
  {
    id: 'cnw-cable-tne-1-5mm-100m',
    supplier: 'CNW',
    category: 'Cables',
    name: 'CNW 1.5mm² Twin and Earth Cable 100m',
    sku: 'CNW-TNE-1.5-100',
    basePrice: 102.00,
  },
  {
    id: 'cnw-cable-tne-2-5mm-100m',
    supplier: 'CNW',
    category: 'Cables',
    name: 'CNW 2.5mm² Twin and Earth Cable 100m',
    sku: 'CNW-TNE-2.5-100',
    basePrice: 135.00,
  },
  {
    id: 'cnw-cable-single-core-6mm-100m',
    supplier: 'CNW',
    category: 'Cables',
    name: 'CNW 6mm² Single Core PVC Cable 100m',
    sku: 'CNW-SC-6-100',
    basePrice: 229.00,
  },
  {
    id: 'cnw-cable-single-core-10mm-100m',
    supplier: 'CNW',
    category: 'Cables',
    name: 'CNW 10mm² Single Core PVC Cable 100m',
    sku: 'CNW-SC-10-100',
    basePrice: 315.00,
  },
  {
    id: 'cnw-cable-single-core-16mm-100m',
    supplier: 'CNW',
    category: 'Cables',
    name: 'CNW 16mm² Single Core PVC Cable 100m',
    sku: 'CNW-SC-16-100',
    basePrice: 415.00,
  },
]

export const EQUIPMENT_CATALOG = [...SPARKY_DIRECT_EQUIPMENT, ...CNW_EQUIPMENT]
